In [1]:
import numpy as np
import pandas as pd

In [2]:
dict1 = {
    "name":["harray","rohan","sadik","subh"],
    "marks":[94,55,99,45],
    "city":["delhi","jaipur","mumbai","bijainagar"],
    
}

In [3]:
df = pd.DataFrame(dict1)

In [4]:
df

     name  marks        city
0  harray     94       delhi
1   rohan     55      jaipur
2   sadik     99      mumbai
3    subh     45  bijainagar

In [5]:
df.to_csv('friends.csv')

In [6]:
df.to_csv('friends_no_index.csv',index=False)

In [7]:
df.head(2)

     name  marks    city
0  harray     94   delhi
1   rohan     55  jaipur

In [8]:
df.tail(2)

    name  marks        city
2  sadik     99      mumbai
3   subh     45  bijainagar

In [9]:
df.describe()

           marks
count   4.000000
mean   73.250000
std    27.232028
min    45.000000
25%    52.500000
50%    74.500000
75%    95.250000
max    99.000000

In [10]:
train = pd.read_csv('practice.csv')

In [11]:
train

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,train_no,train_name,source_station,destination_station,departure_time,arrival_time,distance_km,avg_speed_kmph
0,0,0,0,0,12951,Mumbai Rajdhani Express,Mumbai Central,New Delhi,16:00,08:35,1384,50
1,1,1,1,1,12002,Shatabdi Express,New Delhi,Lucknow,06:10,12:25,512,85
2,2,2,2,2,22975,Jaipur Superfast Express,Jaipur,Mumbai Bandra,14:20,11:40,1160,75
3,3,3,3,3,15645,Guwahati Express,Guwahati,Kolkata,18:30,07:15,1030,70
4,4,4,4,4,19019,Dehradun Express,Dehradun,Delhi Sarai Rohilla,22:15,05:40,305,65

In [12]:
train['avg_speed_kmph'][0] = 50

C:\Users\HP\AppData\Local\Temp\ipykernel_18884\4195310370.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  train['avg_speed_kmph'][0] = 50
C:\Users\HP\AppData\Local\Temp\ipykernel_18884\4195310370.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train['avg_speed_kmph'][0] = 50

In [13]:
train

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,train_no,train_name,source_station,destination_station,departure_time,arrival_time,distance_km,avg_speed_kmph
0,0,0,0,0,12951,Mumbai Rajdhani Express,Mumbai Central,New Delhi,16:00,08:35,1384,50
1,1,1,1,1,12002,Shatabdi Express,New Delhi,Lucknow,06:10,12:25,512,85
2,2,2,2,2,22975,Jaipur Superfast Express,Jaipur,Mumbai Bandra,14:20,11:40,1160,75
3,3,3,3,3,15645,Guwahati Express,Guwahati,Kolkata,18:30,07:15,1030,70
4,4,4,4,4,19019,Dehradun Express,Dehradun,Delhi Sarai Rohilla,22:15,05:40,305,65

In [14]:
train.to_csv('practice.csv')

In [15]:
train.index = ['first','second','third','fourth','fifth']

In [16]:
train

,Unnamed: 0.3,Unnamed: 0.2,Unnamed: 0.1,Unnamed: 0,train_no,train_name,source_station,destination_station,departure_time,arrival_time,distance_km,avg_speed_kmph
first,0,0,0,0,12951,Mumbai Rajdhani Express,Mumbai Central,New Delhi,16:00,08:35,1384,50
second,1,1,1,1,12002,Shatabdi Express,New Delhi,Lucknow,06:10,12:25,512,85
third,2,2,2,2,22975,Jaipur Superfast Express,Jaipur,Mumbai Bandra,14:20,11:40,1160,75
fourth,3,3,3,3,15645,Guwahati Express,Guwahati,Kolkata,18:30,07:15,1030,70
fifth,4,4,4,4,19019,Dehradun Express,Dehradun,Delhi Sarai Rohilla,22:15,05:40,305,65

In [17]:
ser = pd.Series(np.random.rand(34))

In [18]:
type(ser)

pandas.core.series.Series

In [19]:
newdf = pd.DataFrame(np.random.rand(334,5),index=np.arange(334))

In [20]:
type(newdf)
newdf.head()

          0         1         2         3         4
0  0.537421  0.934870  0.321599  0.623413  0.372691
1  0.183266  0.644520  0.091791  0.802502  0.750675
2  0.412695  0.851438  0.725088  0.916715  0.404327
3  0.134150  0.891404  0.028862  0.361823  0.619850
4  0.003658  0.143975  0.286651  0.718352  0.347327

In [21]:
newdf.describe()

                0           1           2           3           4
count  334.000000  334.000000  334.000000  334.000000  334.000000
mean     0.500695    0.448914    0.526630    0.491507    0.497284
std      0.287102    0.285986    0.287576    0.296803    0.297146
min      0.001642    0.002957    0.005688    0.010286    0.001665
25%      0.249916    0.209091    0.302567    0.249016    0.235785
50%      0.501902    0.407607    0.525589    0.456104    0.463680
75%      0.746922    0.686198    0.771162    0.752749    0.750653
max      0.992986    0.997603    0.999409    0.999790    0.999769

In [22]:
newdf.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [23]:
newdf[0][0]= "sadik"

C:\Users\HP\AppData\Local\Temp\ipykernel_18884\4115365061.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf[0][0]= "sadik"
C:\Users\HP\AppData\Local\Temp\ipykernel_18884\4115365061.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'sadik' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  newdf[0][0]= "sadik"

In [24]:
newdf.head()

          0         1         2         3         4
0     sadik  0.934870  0.321599  0.623413  0.372691
1  0.183266  0.644520  0.091791  0.802502  0.750675
2  0.412695  0.851438  0.725088  0.916715  0.404327
3   0.13415  0.891404  0.028862  0.361823  0.619850
4  0.003658  0.143975  0.286651  0.718352  0.347327

In [25]:
newdf.index

Index([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,
       ...
       324, 325, 326, 327, 328, 329, 330, 331, 332, 333],
      dtype='int64', length=334)

In [26]:
newdf.columns

RangeIndex(start=0, stop=5, step=1)

In [27]:
newdf.to_numpy()

array([['sadik', 0.9348701410736625, 0.321598916392395,
        0.6234129755600174, 0.3726912571284241],
       [0.18326565642541137, 0.644519896019416, 0.09179123716175519,
        0.8025023540573546, 0.7506751474465129],
       [0.41269538129393113, 0.8514381837634877, 0.7250881504313839,
        0.9167149316086055, 0.4043266984221142],
       ...,
       [0.6638369415046346, 0.17874408475384918, 0.957286026122559,
        0.09533564221306179, 0.16993885444959878],
       [0.5167743586059677, 0.06369900738181355, 0.26736687923720814,
        0.4764376988216391, 0.14291211434883722],
       [0.45020843196327387, 0.26179882521980236, 0.9859202202585176,
        0.6670046344281019, 0.7197752102962898]],
      shape=(334, 5), dtype=object)

In [28]:
newdf[0][0]= 0.5

In [29]:
newdf.head()

          0         1         2         3         4
0       0.5  0.934870  0.321599  0.623413  0.372691
1  0.183266  0.644520  0.091791  0.802502  0.750675
2  0.412695  0.851438  0.725088  0.916715  0.404327
3   0.13415  0.891404  0.028862  0.361823  0.619850
4  0.003658  0.143975  0.286651  0.718352  0.347327

In [30]:
newdf.T

,0,1,2,3,4,5,6,7,8,9,...,324,325,326,327,328,329,330,331,332,333
0,0.5,0.183266,0.412695,0.13415,0.003658,0.539755,0.778179,0.36675,0.006645,0.959223,...,0.592197,0.480523,0.736436,0.658914,0.608993,0.033677,0.025571,0.663837,0.516774,0.450208
1,0.93487,0.64452,0.851438,0.891404,0.143975,0.505524,0.182047,0.986584,0.943571,0.394827,...,0.976524,0.042095,0.035711,0.447545,0.526439,0.480257,0.14109,0.178744,0.063699,0.261799
2,0.321599,0.091791,0.725088,0.028862,0.286651,0.320449,0.562765,0.623261,0.707152,0.14118,...,0.652864,0.986385,0.909109,0.58319,0.416864,0.763335,0.189743,0.957286,0.267367,0.98592
3,0.623413,0.802502,0.916715,0.361823,0.718352,0.115052,0.26127,0.361037,0.456521,0.79884,...,0.896031,0.358786,0.15596,0.391016,0.163004,0.112669,0.717957,0.095336,0.476438,0.667005
4,0.372691,0.750675,0.404327,0.61985,0.347327,0.659572,0.947828,0.178979,0.555657,0.204783,...,0.239311,0.444107,0.051984,0.996546,0.051003,0.553894,0.168952,0.169939,0.142912,0.719775

In [31]:
newdf

            0         1         2         3         4
0         0.5  0.934870  0.321599  0.623413  0.372691
1    0.183266  0.644520  0.091791  0.802502  0.750675
2    0.412695  0.851438  0.725088  0.916715  0.404327
3     0.13415  0.891404  0.028862  0.361823  0.619850
4    0.003658  0.143975  0.286651  0.718352  0.347327
..        ...       ...       ...       ...       ...
329  0.033677  0.480257  0.763335  0.112669  0.553894
330  0.025571  0.141090  0.189743  0.717957  0.168952
331  0.663837  0.178744  0.957286  0.095336  0.169939
332  0.516774  0.063699  0.267367  0.476438  0.142912
333  0.450208  0.261799  0.985920  0.667005  0.719775

[334 rows x 5 columns]

In [32]:
newdf.sort_index(axis=1,ascending=False)

            4         3         2         1         0
0    0.372691  0.623413  0.321599  0.934870       0.5
1    0.750675  0.802502  0.091791  0.644520  0.183266
2    0.404327  0.916715  0.725088  0.851438  0.412695
3    0.619850  0.361823  0.028862  0.891404   0.13415
4    0.347327  0.718352  0.286651  0.143975  0.003658
..        ...       ...       ...       ...       ...
329  0.553894  0.112669  0.763335  0.480257  0.033677
330  0.168952  0.717957  0.189743  0.141090  0.025571
331  0.169939  0.095336  0.957286  0.178744  0.663837
332  0.142912  0.476438  0.267367  0.063699  0.516774
333  0.719775  0.667005  0.985920  0.261799  0.450208

[334 rows x 5 columns]

In [33]:
newdf.head()

          0         1         2         3         4
0       0.5  0.934870  0.321599  0.623413  0.372691
1  0.183266  0.644520  0.091791  0.802502  0.750675
2  0.412695  0.851438  0.725088  0.916715  0.404327
3   0.13415  0.891404  0.028862  0.361823  0.619850
4  0.003658  0.143975  0.286651  0.718352  0.347327

In [34]:
type(newdf[0])

pandas.core.series.Series

In [35]:
newdf2=newdf.copy()

In [36]:
newdf2[0][0]=9829

C:\Users\HP\AppData\Local\Temp\ipykernel_18884\3156736181.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  newdf2[0][0]=9829
C:\Users\HP\AppData\Local\Temp\ipykernel_18884\3156736181.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  newdf2[0][0]=9829

In [37]:
newdf

            0         1         2         3         4
0         0.5  0.934870  0.321599  0.623413  0.372691
1    0.183266  0.644520  0.091791  0.802502  0.750675
2    0.412695  0.851438  0.725088  0.916715  0.404327
3     0.13415  0.891404  0.028862  0.361823  0.619850
4    0.003658  0.143975  0.286651  0.718352  0.347327
..        ...       ...       ...       ...       ...
329  0.033677  0.480257  0.763335  0.112669  0.553894
330  0.025571  0.141090  0.189743  0.717957  0.168952
331  0.663837  0.178744  0.957286  0.095336  0.169939
332  0.516774  0.063699  0.267367  0.476438  0.142912
333  0.450208  0.261799  0.985920  0.667005  0.719775

[334 rows x 5 columns]

In [38]:
newdf.loc[0,0]=875

In [39]:
newdf.head(2)

          0        1         2         3         4
0       875  0.93487  0.321599  0.623413  0.372691
1  0.183266  0.64452  0.091791  0.802502  0.750675

In [40]:
newdf.columns = list('ABCDE')

In [41]:
newdf

            A         B         C         D         E
0         875  0.934870  0.321599  0.623413  0.372691
1    0.183266  0.644520  0.091791  0.802502  0.750675
2    0.412695  0.851438  0.725088  0.916715  0.404327
3     0.13415  0.891404  0.028862  0.361823  0.619850
4    0.003658  0.143975  0.286651  0.718352  0.347327
..        ...       ...       ...       ...       ...
329  0.033677  0.480257  0.763335  0.112669  0.553894
330  0.025571  0.141090  0.189743  0.717957  0.168952
331  0.663837  0.178744  0.957286  0.095336  0.169939
332  0.516774  0.063699  0.267367  0.476438  0.142912
333  0.450208  0.261799  0.985920  0.667005  0.719775

[334 rows x 5 columns]

In [42]:
newdf.loc[0,'A']=999

In [43]:
newdf

            A         B         C         D         E
0         999  0.934870  0.321599  0.623413  0.372691
1    0.183266  0.644520  0.091791  0.802502  0.750675
2    0.412695  0.851438  0.725088  0.916715  0.404327
3     0.13415  0.891404  0.028862  0.361823  0.619850
4    0.003658  0.143975  0.286651  0.718352  0.347327
..        ...       ...       ...       ...       ...
329  0.033677  0.480257  0.763335  0.112669  0.553894
330  0.025571  0.141090  0.189743  0.717957  0.168952
331  0.663837  0.178744  0.957286  0.095336  0.169939
332  0.516774  0.063699  0.267367  0.476438  0.142912
333  0.450208  0.261799  0.985920  0.667005  0.719775

[334 rows x 5 columns]

In [44]:
newdf.loc[0,0]=999545

In [45]:
newdf

            A         B         C         D         E         0
0         999  0.934870  0.321599  0.623413  0.372691  999545.0
1    0.183266  0.644520  0.091791  0.802502  0.750675       NaN
2    0.412695  0.851438  0.725088  0.916715  0.404327       NaN
3     0.13415  0.891404  0.028862  0.361823  0.619850       NaN
4    0.003658  0.143975  0.286651  0.718352  0.347327       NaN
..        ...       ...       ...       ...       ...       ...
329  0.033677  0.480257  0.763335  0.112669  0.553894       NaN
330  0.025571  0.141090  0.189743  0.717957  0.168952       NaN
331  0.663837  0.178744  0.957286  0.095336  0.169939       NaN
332  0.516774  0.063699  0.267367  0.476438  0.142912       NaN
333  0.450208  0.261799  0.985920  0.667005  0.719775       NaN

[334 rows x 6 columns]

In [46]:
newdf = newdf.drop(0,axis=1)

In [47]:
newdf

            A         B         C         D         E
0         999  0.934870  0.321599  0.623413  0.372691
1    0.183266  0.644520  0.091791  0.802502  0.750675
2    0.412695  0.851438  0.725088  0.916715  0.404327
3     0.13415  0.891404  0.028862  0.361823  0.619850
4    0.003658  0.143975  0.286651  0.718352  0.347327
..        ...       ...       ...       ...       ...
329  0.033677  0.480257  0.763335  0.112669  0.553894
330  0.025571  0.141090  0.189743  0.717957  0.168952
331  0.663837  0.178744  0.957286  0.095336  0.169939
332  0.516774  0.063699  0.267367  0.476438  0.142912
333  0.450208  0.261799  0.985920  0.667005  0.719775

[334 rows x 5 columns]

In [48]:
newdf.loc[[1,2],['C','D']]

          C         D
1  0.091791  0.802502
2  0.725088  0.916715

In [49]:
newdf.head()

          A         B         C         D         E
0       999  0.934870  0.321599  0.623413  0.372691
1  0.183266  0.644520  0.091791  0.802502  0.750675
2  0.412695  0.851438  0.725088  0.916715  0.404327
3   0.13415  0.891404  0.028862  0.361823  0.619850
4  0.003658  0.143975  0.286651  0.718352  0.347327

In [50]:
newdf.loc[[1,2],:]

          A         B         C         D         E
1  0.183266  0.644520  0.091791  0.802502  0.750675
2  0.412695  0.851438  0.725088  0.916715  0.404327

In [51]:
newdf.loc[:,['C','D']]

            C         D
0    0.321599  0.623413
1    0.091791  0.802502
2    0.725088  0.916715
3    0.028862  0.361823
4    0.286651  0.718352
..        ...       ...
329  0.763335  0.112669
330  0.189743  0.717957
331  0.957286  0.095336
332  0.267367  0.476438
333  0.985920  0.667005

[334 rows x 2 columns]

In [52]:
newdf.loc[(newdf['A']<0.3)&(newdf['C']>0.1)]

            A         B         C         D         E
4    0.003658  0.143975  0.286651  0.718352  0.347327
8    0.006645  0.943571  0.707152  0.456521  0.555657
11   0.025916  0.672507  0.424143  0.026941  0.625966
22   0.045215  0.916163  0.199714  0.340383  0.577208
27   0.235825  0.228439  0.898492  0.508093  0.910286
..        ...       ...       ...       ...       ...
313  0.160299  0.827024  0.831917  0.013910  0.518120
322  0.270652  0.833345  0.209166  0.010511  0.775222
323  0.025348  0.507516  0.263656  0.231538  0.151425
329  0.033677  0.480257  0.763335  0.112669  0.553894
330  0.025571  0.141090  0.189743  0.717957  0.168952

[88 rows x 5 columns]

In [53]:
newdf.iloc[0,4]

np.float64(0.3726912571284241)

In [54]:
newdf.iloc[[0,4],[1,2]]

          B         C
0  0.934870  0.321599
4  0.143975  0.286651

In [55]:
newdf.head(3)

          A         B         C         D         E
0       999  0.934870  0.321599  0.623413  0.372691
1  0.183266  0.644520  0.091791  0.802502  0.750675
2  0.412695  0.851438  0.725088  0.916715  0.404327

In [56]:
newdf.drop(['A','D'],axis=1, inplace=True)

In [57]:
newdf

            B         C         E
0    0.934870  0.321599  0.372691
1    0.644520  0.091791  0.750675
2    0.851438  0.725088  0.404327
3    0.891404  0.028862  0.619850
4    0.143975  0.286651  0.347327
..        ...       ...       ...
329  0.480257  0.763335  0.553894
330  0.141090  0.189743  0.168952
331  0.178744  0.957286  0.169939
332  0.063699  0.267367  0.142912
333  0.261799  0.985920  0.719775

[334 rows x 3 columns]

In [58]:
newdf.head(3)

          B         C         E
0  0.934870  0.321599  0.372691
1  0.644520  0.091791  0.750675
2  0.851438  0.725088  0.404327

In [59]:
newdf.reset_index(drop=True,inplace=True)

In [60]:
newdf.head(3)

          B         C         E
0  0.934870  0.321599  0.372691
1  0.644520  0.091791  0.750675
2  0.851438  0.725088  0.404327

In [61]:
newdf.loc[:,['B']] =56

In [62]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: B, Length: 334, dtype: bool

In [63]:
newdf['B'].isnull()

0      False
1      False
2      False
3      False
4      False
       ...
329    False
330    False
331    False
332    False
333    False
Name: B, Length: 334, dtype: bool

In [64]:
newdf.head()

      B         C         E
0  56.0  0.321599  0.372691
1  56.0  0.091791  0.750675
2  56.0  0.725088  0.404327
3  56.0  0.028862  0.619850
4  56.0  0.286651  0.347327

In [65]:
data = {
    "name": ["Harry", "Rohan", "Sadik", "Harry"],
    "toy": ["Car", np.nan, "Train", np.nan],
    "born": [2001, 2000, np.nan, 2003]
}

df = pd.DataFrame(data)

In [66]:
df.head( )

    name    toy    born
0  Harry    Car  2001.0
1  Rohan    NaN  2000.0
2  Sadik  Train     NaN
3  Harry    NaN  2003.0

In [67]:
df.dropna(how='all',axis=1)

    name    toy    born
0  Harry    Car  2001.0
1  Rohan    NaN  2000.0
2  Sadik  Train     NaN
3  Harry    NaN  2003.0

In [68]:
df.drop_duplicates(subset=['name'],keep=False)

    name    toy    born
1  Rohan    NaN  2000.0
2  Sadik  Train     NaN

In [69]:
df.shape

(4, 3)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   toy     2 non-null      object
 2   born    3 non-null      float64
dtypes: float64(1), object(2)
memory usage: 228.0+ bytes

In [71]:
df['toy'].value_counts(dropna=True)

toy
Car      1
Train    1
Name: count, dtype: int64

In [72]:
df.isnull()

    name    toy   born
0  False  False  False
1  False   True  False
2  False  False   True
3  False   True  False

In [73]:
#create a dataframe which containes only intergers with 3 rows and 2 columns 
#run following dataframe methods on them:

In [78]:
data = pd.read_excel('data.xlsx')

In [79]:
data.iloc[0,0]=34

In [81]:
data.to_excel('data.xlsx')

In [82]:
data

   Unnamed: 0   Name    Toy    Born        City
0          34     34    Car  2001.0       Delhi
1           1  Rohan    NaN  2000.0      Jaipur
2           2  Sadik  Train     NaN      Mumbai
3           3   Subh  Robot  2003.0  Bijainagar